name: Rust CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1
  LOG_FILE: log/logfile.txt
  LOG_LEVEL: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: bash run install
    - name: Cargo Build for Python Implementation
      run: cargo build --release --target x86_64-pc-windows-msvc
    - name: DLL for Python Implementation
      run: cargo rustc --lib --release --target x86_64-pc-windows-msvc -- -C link-args="/DLL /IMPLIB:my_lib.lib"
    - name: Build
      run: bash run build
    - name: Cargo Test for Python Implementation
      run: cargo test --release --target x86_64-pc-windows-msvc
    - name: Test
      run: bash run test
    - name: Lint
      run: cargo clippy -- -D warnings

